### ISSUE TITLE
incorrect blocks opening in UEB

### ISSUE THREAD

**Issue by alexb-hw** [civodulab/mathml2braille#2]
Hi, just noticed that the blocks in UEB are defined in the .js as: 
```
             'blocks': {
                 'open': '-1-2-6-',
                 'close': '-3-4-5-'
             },
```
which then produces three braille characters. 

I think it's meant to be :
 ```
            'blocks': {
                 'open': '-126-',
                 'close': '-345-'
             },

```
but maybe it's even better if left empty, like in Nemeth.   
```
             'blocks': {
                 'open': '',
                 'close': ''
             },

```

Cheers,
Alex.

**Comment by civodulab** [comment]
You're absolutely right, it's as you think (-126- and -345-)
Thanks Alex
